PosWebApp/Controllers/BranchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using POS.BLL.Setup;
using POS.Models.Setup;
using POS.Models.ViewModel;

namespace PosWebApp.Controllers
{
    public class BranchController : Controller
    {
        Branch branchEn = new Branch();
        BranchVM branchVm = new BranchVM();
        BranchManager _branchBll = new BranchManager();

        // GET: Branch
        public ActionResult Index()
        {
            branchVm.Branches = _branchBll.GetBranchList().OrderByDescending(x => x.Date).ToList();
            return View(branchVm.Branches);
        }

        public ActionResult Create()
        {
            branchVm.SelectList = _branchBll.GetBranchSelectList();
            branchVm.Code = _branchBll.GetBranchCode();
            return View(branchVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BranchVM branchVM)
        {
            branchVM.Date = DateTime.Now;
            Branch branch = Mapper.Map<Branch>(branchVM);
            if (ModelState.IsValid)
            {
                if (_branchBll.IsBranchSaved(branch))
                {
                    return RedirectToAction("Index");
                }
            }

            branchVm.SelectList = _branchBll.GetBranchSelectList();
            branchVm.Code = _branchBll.GetBranchCode();
            return View(branchVm);
        }



        public ActionResult Details(long id)
        {
            Branch branch = _branchBll.FindBranch(id);
            BranchVM branchVm = Mapper.Map<BranchVM>(branch);
            return PartialView("_Details", branchVm);
        }

        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            branchEn = _branchBll.FindBranch(id);
            BranchVM bnchVm = Mapper.Map<BranchVM>(branchEn);

            if (bnchVm == null)
            {
                return HttpNotFound();
            }

            bnchVm.SelectList = _branchBll.GetBranchSelectList();
            return View(bnchVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(BranchVM bnchVm)
        {
            Branch branch = Mapper.Map<Branch>(bnchVm);
            if (ModelState.IsValid)
            {
                if (_branchBll.IsBranchUpdated(branch))
                {
                    return RedirectToAction("Index");
                }
            }

            return View(bnchVm);
        }

        public ActionResult Delete(long id)
        {
            var isDeleted = _branchBll.IsBranchDeleted(id);

            return Json(isDeleted, JsonRequestBehavior.AllowGet);
        }

        public ActionResult IsUniqueCode(string Code, string initialCode)
        {
            var isUnique = _branchBll.IsUniqueCode(Code, initialCode);
            return Json(isUnique, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetAll()
        {
            return Json(_branchBll.GetBranchList(), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetByOrganization(int organizationId)
        {
            return Json(_branchBll.GetByOrgId(organizationId), JsonRequestBehavior.AllowGet);
        }
    }
}

PosWebApp/Views/Branch/Create.cshtml
@model POS.Models.ViewModel.BranchVM

@{
    ViewBag.Title = "Add Branch";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Branch Create</h2>
<hr />


@using (Html.BeginForm("Create", "Branch", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.OrganizationId, new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Html.DropDownListFor(model => model.OrganizationId, Model.SelectList, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.OrganizationId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Code, new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Html.TextBoxFor(model => model.Code, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Contact, new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Html.TextBoxFor(model => model.Contact, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Contact, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Address, new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Html.TextAreaFor(model => model.Address, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @*@Scripts.Render("~/bundles/jqueryval")*@
    <script src="~/Scripts/Custom/Branch.js"></script>
}

PosWebApp/Views/Branch/Edit.cshtml
@model POS.Models.ViewModel.BranchVM

@{
    ViewBag.Title = "Edit Branch";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Branch Edit</h2>
<hr />


@using (Html.BeginForm("Edit", "Branch", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
            @Html.HiddenFor(model => model.Date)
            @Html.Hidden("initialCode", @Model.Code)

        <div class="form-group">
            @Html.LabelFor(model => model.OrganizationId, new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Html.DropDownListFor(model => model.OrganizationId, Model.SelectList, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.OrganizationId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Code, new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Html.TextBoxFor(model => model.Code, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Contact, new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Html.TextBoxFor(model => model.Contact, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Contact, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Address, new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Html.TextAreaFor(model => model.Address, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-primary" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @*@Scripts.Render("~/bundles/jqueryval")*@
    <script src="~/Scripts/Custom/Branch.js"></script>
}

PosWebApp/Views/Branch/Index.cshtml
@model IEnumerable<POS.Models.Setup.Branch>

@{
    ViewBag.Title = "Branch";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.ActionLink("Add Branch", "Create", null, new { @class = "btn btn-primary" })
<br /><br /><br />

<table class="table table-striped table-hover table-bordered" id="branchTable">
    <thead>
        <tr>
            <th>@Html.DisplayName("SL")</th>
            <th>Organization</th>
            <th>@Html.DisplayNameFor(model => model.Code)</th>
            <th>@Html.DisplayNameFor(model => model.Address)</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @{ int sl = 0; }
        @foreach (var item in Model)
        {
            sl++;
            <tr id="row_@sl">
                <td>@Html.DisplayFor(modelItem => sl)</td>
                <td>@Html.DisplayFor(modelItem => item.Organizations.Name)</td>
                <td>@Html.DisplayFor(modelItem => item.Code)</td>
                <td>@Html.DisplayFor(modelItem => item.Address)</td>
                <td>
                    <a class="btn btn-primary btn-sm" onclick="BranchDetails(@item.Id)"
                       href='#'>
                        <i class="glyphicon glyphicon-eye-open"></i>
                    </a>
                    <a class="btn btn-success btn-sm"
                       href='@Url.Action("Edit", "Branch", new {id = item.Id})'>
                        <i class="glyphicon glyphicon-edit"></i>
                    </a>
                    <a class="btn btn-danger btn-sm" onclick="ConfirmDeleteBranch(@item.Id,@sl)"
                       href="#">
                        <i class="glyphicon glyphicon-trash"></i>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

<!--Start Details Modal -->
<div class="modal fade" id="detailsModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="text-primary">Branch Details</h3>
            </div>
            <div class="modal-body" id="detailsModalContent">
            </div>
            <div class="modal-footer">
                <a href="#" class="btn btn-default" data-dismiss="modal">Cancel</a>
            </div>
        </div>
    </div>
</div>
<!--End Details Modal -->
<!-- Start Delete Modal -->
<div class="modal fade" id="confirmDeleteModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="text-danger">Confirmation</h3>
            </div>
            <div class="modal-body text-center">
                <h5>Are you sure want to delete this branch ? </h5>
            </div>
            <div class="modal-footer">
                <a href="#" class="btn btn-danger" onclick="DeleteBranch()">Confirm</a>
                <a href="#" class="btn btn-default" data-dismiss="modal">Cancel</a>
            </div>
        </div>
    </div>
</div>

<input type="hidden" id="hiddenBranchId" />
<input type="hidden" id="hiddenBranchSl" />
<!-- End Delete Modal -->

<link href="//cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet" />

@section scripts
{
    <script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function(){
            $('#branchTable').DataTable();
        });
    </script>
    <script src="~/Scripts/Custom/Branch.js"></script>
}

PosWebApp/Views/Branch/_Details.cshtml
@model POS.Models.ViewModel.BranchVM

@{
    ViewBag.Title = "Branch";
}
<div class="row">
    <div class="col-md-12">
        <br />
        <h5>
            @Html.Label("Address : ")
            @Html.DisplayFor(model => model.Address)
        </h5>
        <h5>
            @Html.Label("Code : ")
            @Html.DisplayFor(model => model.Code)
        </h5>
    </div>
</div>
<hr/>
<div class="form-group row">
    @Html.LabelFor(model => model.OrganizationId, new { @class = "control-label col-md-4" })
    <span class="control-label col-md-8">
        @Html.DisplayFor(model => model.Organization.Name)
    </span>
</div>
<div class="form-group row">
    @Html.LabelFor(model => model.Contact, new { @class = "control-label col-md-4" })
    <span class="control-label col-md-8">
        @Html.DisplayFor(model => model.Contact)
    </span>
</div>
<div class="form-group row">
    @Html.LabelFor(model => model.Date, new { @class = "control-label col-md-4" })
    <span class="control-label col-md-8">
        @Html.DisplayFor(model => model.Date)
    </span>
</div>