PosWebApp/Controllers/PartyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using POS.BLL.Setup;
using POS.Models.Setup;
using POS.Models.ViewModel;

namespace PosWebApp.Controllers
{
    public class PartyController : Controller
    {
        Party partyEn = new Party();
        PartyVM partyVm = new PartyVM();
        PartyManager _partyBll = new PartyManager();
        ImageManager imageData = new ImageManager();

        // GET: Party
        public ActionResult Index()
        {
            partyVm.Parties = _partyBll.GetPartyList().OrderByDescending(x => x.Date).ToList();
            return View(partyVm.Parties);
        }

        public ActionResult Create()
        {
            partyVm.PreCode = _partyBll.GetPartyPreCode();
            partyVm.Code = _partyBll.GetPartyCode();
            return View(partyVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PartyVM partyVm, HttpPostedFileBase ItemCategoryFile)
        {
            partyVm.Date = DateTime.Now;
            partyVm.Image = imageData.ImageConvertToByte(ItemCategoryFile);

            Party party = Mapper.Map<Party>(partyVm);
            if (ModelState.IsValid)
            {
                if (_partyBll.IsPartySaved(party))
                {
                    return RedirectToAction("Index");
                }
            }

            partyVm.PreCode = _partyBll.GetPartyPreCode();
            partyVm.Code = _partyBll.GetPartyCode();
            return View(partyVm);
        }


        public ActionResult Details(long id)
        {
            Party party = _partyBll.FindParty(id);

            PartyVM partyVm = Mapper.Map<PartyVM>(party);
            return PartialView("_Details", partyVm);
        }

        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            partyEn = _partyBll.FindParty(id);
            PartyVM partyVm = Mapper.Map<PartyVM>(partyEn);

            if (partyVm == null)
            {
                return HttpNotFound();
            }

            return View(partyVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PartyVM partyVm)
        {
            Party party = Mapper.Map<Party>(partyVm);
            if (ModelState.IsValid)
            {
                if (_partyBll.IsPartyUpdated(party))
                {
                    return RedirectToAction("Index");
                }
            }

            return View(partyVm);
        }

        public ActionResult Delete(long id)
        {
            var isDeleted = _partyBll.IsPartyDeleted(id);

            return Json(isDeleted, JsonRequestBehavior.AllowGet);
        }

        public ActionResult IsUniqueName(string Name, string initialName)
        {
            var isUnique = _partyBll.IsUniqueName(Name, initialName);
            return Json(isUnique, JsonRequestBehavior.AllowGet);
        }

        public ActionResult IsUniqueCode(string PreCode, string Code, string initialPreCode, string initialCode)
        {
            var isUnique = _partyBll.IsUniqueCode(PreCode, Code, initialPreCode, initialCode);
            return Json(isUnique, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetAll()
        {
            return Json(_partyBll.GetPartyList(), JsonRequestBehavior.AllowGet);
        }
    }
}

PosWebApp/Views/Party/Create.cshtml
@model POS.Models.ViewModel.PartyVM

@{
    ViewBag.Title = "Add Party";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Party Create</h4>
<hr />


@using (Html.BeginForm("Create", "Party", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.Label("Party Type", new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        <label class="checkbox-inline ">
                            @Html.CheckBoxFor(model => model.IsCustomer)
                            @Html.DisplayNameFor(model => model.IsCustomer)
                        </label>
                        <label class="checkbox-inline ">
                            @Html.CheckBoxFor(model => model.IsSupplier)
                            @Html.DisplayNameFor(model => model.IsSupplier)
                        </label>
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Code, new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        <div class="row">
                            <div class="col-md-5">
                                @Html.TextBoxFor(model => model.PreCode, new { @class = "form-control", @readonly = true })
                            </div>
                            <div class="col-md-4">
                                @Html.TextBoxFor(model => model.Code, new { @class = "form-control" })
                            </div>
                        </div>
                        @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Image, new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        <input type="file" name="ItemCategoryFile" id="itemCategoryFile" />
                        @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
                        <br />
                        <img src="" alt="" id="itemCategoryFilePreview" class="img-responsive" width="200" height="200" />
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.Contact, new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.TextBoxFor(model => model.Contact, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Contact, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Address, new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.TextAreaFor(model => model.Address, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                    </div>
                </div>

            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-8 col-md-4">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @*@Scripts.Render("~/bundles/jqueryval")*@
    <script src="~/Scripts/Custom/Party.js"></script>
<script src="~/Scripts/Custom/Image.js"></script>
}

PosWebApp/Views/Party/Edit.cshtml
@model POS.Models.ViewModel.PartyVM

@{
    ViewBag.Title = "Edit Party";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Party Create</h4>
<hr />


@using (Html.BeginForm("Edit", "Party", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.Image)
        @Html.HiddenFor(model => model.Date)
        @Html.Hidden("initialName", @Model.Name)
        @Html.Hidden("initialPreCode", @Model.PreCode)
        @Html.Hidden("initialCode", @Model.Code)


        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.Label("Party Type", new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        <label class="checkbox-inline ">
                            @Html.CheckBoxFor(model => model.IsCustomer)
                            @Html.DisplayNameFor(model => model.IsCustomer)
                        </label>
                        <label class="checkbox-inline ">
                            @Html.CheckBoxFor(model => model.IsSupplier)
                            @Html.DisplayNameFor(model => model.IsSupplier)
                        </label>
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Code, new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        <div class="row">
                            <div class="col-md-5">
                                @Html.TextBoxFor(model => model.PreCode, new { @class = "form-control", @readonly = true })
                            </div>
                            <div class="col-md-4">
                                @Html.TextBoxFor(model => model.Code, new { @class = "form-control" })
                            </div>
                        </div>
                        @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.Contact, new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.TextBoxFor(model => model.Contact, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Contact, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Address, new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.TextAreaFor(model => model.Address, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                    </div>
                </div>

            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-8 col-md-4">
                <input type="submit" value="Update" class="btn btn-primary" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @*@Scripts.Render("~/bundles/jqueryval")*@
}

PosWebApp/Views/Party/Index.cshtml
@model IEnumerable<POS.Models.Setup.Party>

@{
    ViewBag.Title = "Party";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.ActionLink("Add Party", "Create", null, new { @class = "btn btn-primary" })
<br /><br /><br />

<table class="table table-striped table-hover table-bordered" id="partyTable">
    <thead>
        <tr>
            <th>@Html.DisplayName("SL")</th>
            <th>@Html.DisplayNameFor(model => model.Name)</th>
            <th>@Html.DisplayNameFor(model => model.Code)</th>
            <th>@Html.DisplayNameFor(model => model.Contact)</th>
            <th>@Html.DisplayNameFor(model => model.Address)</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @{ int sl = 0; }
        @foreach (var item in Model)
        {
            sl++;
            <tr id="row_@sl">
                <td>@Html.DisplayFor(modelItem => sl)</td>
                <td>@Html.DisplayFor(modelItem => item.Name)</td>
                <td>
                    @Html.DisplayFor(modelItem => item.PreCode)
                    @Html.DisplayFor(modelItem => item.Code)
                </td>
                <td>@Html.DisplayFor(modelItem => item.Contact)</td>
                <td>@Html.DisplayFor(modelItem => item.Address)</td>
                <td>
                    <a class="btn btn-primary btn-sm" onclick="PartyDetails(@item.Id)"
                       href='#'>
                        <i class="glyphicon glyphicon-eye-open"></i>
                    </a>
                    <a class="btn btn-success btn-sm"
                       href='@Url.Action("Edit", "Party", new {id = item.Id})'>
                        <i class="glyphicon glyphicon-edit"></i>
                    </a>
                    <a class="btn btn-danger btn-sm" onclick="ConfirmDeleteParty(@item.Id,@sl)"
                       href="#">
                        <i class="glyphicon glyphicon-trash"></i>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

<!--Start Details Modal -->
<div class="modal fade" id="detailsModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="text-primary">Party Details</h3>
            </div>
            <div class="modal-body" id="detailsModalContent">
            </div>
            <div class="modal-footer">
                <a href="#" class="btn btn-default" data-dismiss="modal">Cancel</a>
            </div>
        </div>
    </div>
</div>
<!--End Details Modal -->
<!-- Start Delete Modal -->
<div class="modal fade" id="confirmDeleteModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="text-danger">Confirmation</h3>
            </div>
            <div class="modal-body text-center">
                <h5>Are you sure want to delete this Party ? </h5>
            </div>
            <div class="modal-footer">
                <a href="#" class="btn btn-danger" onclick="DeleteParty()">Confirm</a>
                <a href="#" class="btn btn-default" data-dismiss="modal">Cancel</a>
            </div>
        </div>
    </div>
</div>

<input type="hidden" id="hiddenPartyId" />
<input type="hidden" id="hiddenPartySl" />
<!-- End Delete Modal -->

<link href="//cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet" />

@section scripts
{
    <script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function(){
            $('#partyTable').DataTable();
        });
    </script>

    <script src="~/Scripts/Custom/Party.js"></script>
    
}

PosWebApp/Views/Party/_Details.cshtml
@model POS.Models.ViewModel.PartyVM
@{
    ViewBag.Title = "Party";
}
<div class="row">
    <div class="col-md-4">
        @if (Model.Image != null)
        {
            <img src="data:image/jpg;base64,@Convert.ToBase64String(Model.Image)" class="img-responsive" width="150" height="150" />
        }
        else
        {
            <img src="~/Images/product.png" class="img-responsive" width="150" height="150" />
        }
    </div>
    <div class="col-md-8">
        <br />
        <h5>
            @Html.Label("Name : ")
            @Html.DisplayFor(model => model.Name)
        </h5>
        <h5>
            @Html.Label("Code : ")
            @Html.DisplayFor(model => model.PreCode)
            @Html.DisplayFor(model => model.Code)
        </h5>
    </div>
</div>
<br /><br />
<div class="form-group row">
    @Html.Label("Type", new { @class = "control-label col-md-4" })
    <span class="control-label col-md-8">
        @if (Model.IsSupplier && Model.IsCustomer)
        {
            @Html.DisplayNameFor(model => model.IsSupplier)
            @Html.DisplayName(" And ")
            @Html.DisplayNameFor(model => model.IsCustomer)
        }
        else if (Model.IsSupplier)
        {
            @Html.DisplayNameFor(model => model.IsSupplier)
        }
        else if (Model.IsCustomer)
        {
            @Html.DisplayNameFor(model => model.IsCustomer)
        }
    </span>
</div>
<div class="form-group row">
    @Html.LabelFor(model => model.Contact, new { @class = "control-label col-md-4" })
    <span class="control-label col-md-8">
        @Html.DisplayFor(model => model.Contact)
    </span>
</div>
<div class="form-group row">
    @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-4" })
    <span class="control-label col-md-8">
        @Html.DisplayFor(model => model.Email)
    </span>
</div>
<div class="form-group row">
    @Html.LabelFor(model => model.Address, new { @class = "control-label col-md-4" })
    <span class="control-label col-md-8">
        @Html.DisplayFor(model => model.Address)
    </span>
</div>
<div class="form-group row">
    @Html.LabelFor(model => model.Date, new { @class = "control-label col-md-4" })
    <span class="control-label col-md-8">
        @Html.DisplayFor(model => model.Date)
    </span>
</div>